
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mitchq_dbt_transformations'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mitchq_dbt_transformations'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  mitchq_dbt_transformations:

vars: 
  fivetran_log:
    # fivetran_log_database: MITCH
    fivetran_log_schema: FIVETRAN_LOG_MQ

    fivetran_log_using_transformations: false
    fivetran_log_using_triggers: false
 
  facebook_ads_source:
    facebook_ads_schema: FACEBOOK_ADS_MQ_TEST

  google_ads_source:
    google_ads_schema: ADWORDS_MQ_TEST

  linkedin_source:
    linkedin_source_schema: LINKEDIN_ADS

  netsuite_source:
    netsuite_source_schema: NETSUITE_SUITEANALYTICS_MQ_TEST